### ISSUE TITLE
Rails 5: api mode - undefined method `assets`

### ISSUE THREAD

**Issue by movstox** [fgrehm/letter_opener_web#46]
Getting this for clear rails 5 api-only app (`rails new myapp --api`):

```
/home/oivai/.rvm/gems/ruby-2.3.0/bundler/gems/rails-513f72804d80/railties/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined met
hod `assets' for #<Rails::Application::Configuration:0x000000047352b8> (NoMethodError)
Did you mean?  asset_host
        from /home/oivai/.rvm/gems/ruby-2.3.0/bundler/gems/letter_opener_web-55c581e463e7/lib/letter_opener_web/engine.rb:16:in `block in <class:E
ngine>'
        from /home/oivai/.rvm/gems/ruby-2.3.0/bundler/gems/rails-513f72804d80/railties/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/oivai/.rvm/gems/ruby-2.3.0/bundler/gems/rails-513f72804d80/railties/lib/rails/initializable.rb:30:in `run'
        from /home/oivai/.rvm/gems/ruby-2.3.0/bundler/gems/rails-513f72804d80/railties/lib/rails/initializable.rb:55:in `block in run_initializers
'
```

Is there a workaround?
Thank you!

**Comment by fgrehm** [comment]
Not sure yet, I haven't had a chance to look into rails 5 yet =/ But I might guess that you won't be able to use this gem with api-only apps as this gem requires the asset pipeline to be in place (and I think that api mode disables that right?)

**Comment by movstox** [comment]
Yes, probably you are right :|

--

**Comment by fgrehm** [comment]
Well, I'd accept a PR that inlines our JS + CSS and references bootstrap from a CDN so that we don't have a need for the asset pipeline to be in place :smirk: 

WDYT?

**Comment by movstox** [comment]
Let me see, I'm pretty new to this.

--

**Comment by flaviocamilo** [comment]
The instruction found at [rswag issue #12](https://github.com/domaindrivendev/rswag/issues/12) worked for me.
Try to uncomment `require "sprockets/railtie"` in `config/application.rb` and see if it works for you too!

**Comment by ishabo** [comment]
I had the exact same issue installing activeadmin on rails5 --api, and uncommenting 
`require "sprockets/railtie"` in `config/application.rb` solved the problem

**Comment by FreeBreadsticks** [comment]
Thank you @flaviocamilo this solution still works!

**Comment by sauy7** [comment]
@fgrehm I have a fork here: https://github.com/sauy7/letter_opener_web that inlines the Javascript, CSS and images and removes reference to the asset pipeline. It seems to work OK with a Rails 5.2 app I'm running with sprockets removed. If you like it I can create a PR from it.

**Comment by pseudomuto** [comment]
@sauy7 I'd definitely love to drop the dependency on the asset pipeline. PRs are definitely welcome!

**Comment by sauy7** [comment]
PR #83 submitted

**Comment by pseudomuto** [comment]
Resolved by @sauy7 in #83

**Comment by dafnalia** [comment]
In the meantime, I added the following to my Gemfile:

gem 'letter_opener_web', github: 'fgrehm/letter_opener_web', ref: 'd6c6455'

**Comment by belgoros** [comment]
It still fails for Rails API `5.2.2` version as follows when just running `rails generate apitome:install`
```
/Users/Serguei/.rvm/gems/ruby-2.6.1/gems/railties-5.2.1/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Engine::Configuration:0x00007ff03542cc78> (NoMethodError)
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/apitome-0.2.1/lib/apitome/engine.rb:8:in `<class:Engine>'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/apitome-0.2.1/lib/apitome/engine.rb:2:in `<module:Apitome>'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/apitome-0.2.1/lib/apitome/engine.rb:1:in `<main>'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/apitome-0.2.1/lib/apitome.rb:7:in `<main>'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
	from /Users/Serguei/projects/rails/draft-api/config/application.rb:18:in `<top (required)>'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by backnotprop** [comment]
I get this error only when I _accidentally_ include a ui-basaed gem in the Gemfile.

ie forgetting to remove https://github.com/brentd/xray-rails

<img width="854" alt="Screen Shot 2019-09-08 at 8 41 07 AM" src="https://user-images.githubusercontent.com/7244317/64488319-82f84b80-d214-11e9-8f5c-0ec279a5fa14.png">

**Comment by ViXP** [comment]
It is still reproducing for me.
**Rails 5.2.3 (API mode)
letter_opener_web 1.3.4**
```
undefined method assets' for #<Rails::Application::Configuration:0x0000562ec9be1128>
```
If I'm adding `require 'sprockets/railtie'` to _application.rb_, the next error I'm experiencing is 
```
Expected to find a manifest file in `app/assets/config/manifest.js`
```
So I need to create this file. It's not a good option for me, because I'm writing the application based on engines and completely don't have `app` directory.
Any ideas?

**Comment by Csega** [comment]
I have the same issue as ViXP.
